In [2]:
import numpy as np
from nibabel.testing import data_path
import matplotlib.pyplot as plt

In [3]:
import nibabel as nib

In [4]:
file = nib.load('deco_parc.dlabel.nii')
file1 = nib.load("Mean.339.MyelinMap_BC_MSMAll.32k_fs_LR.dscalar.nii")
print(file.header)

pixdim[1,2,3] should be non-zero; setting 0 dims to 1


In [5]:
data = file.get_fdata()
data1 = file1.get_fdata()
data

memmap([[31., 15., 16., ..., 54., 54., 54.]])

In [6]:
type(data)


numpy.memmap

In [7]:
z = np.asarray(data)
z = z[0]
z
z1 = np.asarray(data1)
z1 = z1[0]

In [8]:
result = np.unique(data, return_counts = True)
result1 = np.unique(data1, return_counts = True)

In [9]:
z1

array([1.34754133, 1.34526181, 1.39597261, ..., 1.23321581, 1.23045897,
       1.23129427])

In [10]:
data1[0][9]

1.397700548171997

In [11]:
import matplotlib.pyplot as plt
x = np.asarray(result)
x

array([[0.000e+00, 1.000e+00, 2.000e+00, 3.000e+00, 4.000e+00, 5.000e+00,
        6.000e+00, 7.000e+00, 8.000e+00, 9.000e+00, 1.000e+01, 1.100e+01,
        1.200e+01, 1.300e+01, 1.400e+01, 1.500e+01, 1.600e+01, 1.700e+01,
        1.800e+01, 1.900e+01, 2.000e+01, 2.100e+01, 2.200e+01, 2.300e+01,
        2.400e+01, 2.500e+01, 2.600e+01, 2.700e+01, 2.800e+01, 2.900e+01,
        3.000e+01, 3.100e+01, 3.200e+01, 3.300e+01, 3.400e+01, 3.500e+01,
        3.600e+01, 3.700e+01, 3.800e+01, 3.900e+01, 4.000e+01, 4.100e+01,
        4.200e+01, 4.300e+01, 4.400e+01, 4.500e+01, 4.600e+01, 4.700e+01,
        4.800e+01, 4.900e+01, 5.000e+01, 5.100e+01, 5.200e+01, 5.300e+01,
        5.400e+01, 5.500e+01, 5.600e+01, 5.700e+01, 5.800e+01, 5.900e+01,
        6.000e+01, 6.100e+01, 6.200e+01, 6.300e+01, 6.400e+01, 6.500e+01,
        6.600e+01],
       [2.772e+03, 1.810e+02, 6.640e+02, 1.690e+02, 6.800e+01, 8.750e+02,
        1.980e+02, 1.233e+03, 2.052e+03, 8.760e+02, 1.772e+03, 1.557e+03,
        4.660e+02,

In [12]:
copy = data1.copy()
copy.shape

(1, 59412)

In [27]:
value_average = [None]*59412
#value_average = [None]*30000
averages = []




for i in range(66):
    indicies = [x[0] for x in enumerate(data[0]) if x[1] == i]
    values = []
    for index in indicies:
        values.append(data1[0][index])
        values_arr = np.asarray(values)
        avg = np.average(values_arr)
     
        if index < 300000:
            value_average[index] = float(avg)
    averages.append(avg)
    


In [30]:
import os
a

[1.2854152199251827,
 1.227792130649419,
 1.4424376613404377,
 1.0469023610007833,
 1.1828243136405945,
 1.303312127658299,
 1.6625959042346838,
 1.4629483030563626,
 1.3641776884624601,
 1.2202533857735325,
 1.303932936950408,
 1.282084602841063,
 1.334848750046906,
 1.2365140146679348,
 1.3103471192878875,
 1.4341471843923876,
 1.4490561021445587,
 1.2952952314731745,
 1.2726356679813702,
 1.2835783559127658,
 1.2291798391687265,
 1.2069222687264165,
 1.2363421778580874,
 1.1435256795498288,
 1.1453369250063037,
 1.2293931179523467,
 1.2093989826032687,
 1.474141604021976,
 1.5563684894804612,
 1.5185228665191006,
 1.3588650345802307,
 1.529848176889469,
 1.3269816937030858,
 1.3099656561972746,
 1.3178617811488533,
 1.3426531807581583,
 1.5270863322545762,
 1.3465391690818427,
 1.4978371237415866,
 1.5709637108851562,
 1.4957923708843583,
 1.2268548149242293,
 1.2202711088652163,
 1.144026834389259,
 1.1521108506018656,
 1.2591329048101318,
 1.2016449919494065,
 1.2261906664643512,


In [15]:
value_average = np.asanyarray(value_average, dtype = np.float64)
value_average = np.reshape(value_average, (1, 59412))
value_average
#copy

array([[1.34754133, 1.34526181, 1.39597261, ..., 1.22935406, 1.2293552 ,
        1.22935721]])

In [16]:
os.getcwd()

'C:\\Users\\Kellen\\Desktop\\Research\\Experiment3'

In [17]:
path = os.path.join(os.getcwd(), "average1.nii")
img = nib.cifti2.cifti2.Cifti2Image(value_average)

In [18]:
nib.save(img, path)

In [19]:
print(nib.load(path).header)


In [20]:
import cifti

In [21]:
axes, (axis1, axis2)= cifti.read('deco_parc.dlabel.nii')

pixdim[1,2,3] should be non-zero; setting 0 dims to 1


In [22]:
cifti.write("average4.nii", value_average, (axis1, axis2))